---
title: "Introduction to Multiomics Data Integration and Visualisation"
author: Jacques SERIZAY
date: "`r Sys.Date()`"
---

# Introduction

Aging is the time-dependent functional decline that affects most 
living organisms. The accumulation of cellular damage 
is widely considered to be the general cause of aging, which explains
why the studies from the last three decades have mostly focused on 
the cellular aspects of aging. Currently, the aging hallmarks are: 
genomic instability, telomere attrition, epigenetic alterations, 
loss of proteostasis, deregulated nutrient sensing, mitochondrial 
dysfunction, cellular senescence, stem cell exhaustion, 
and altered intercellular communication. 

However, aging should not be seen as a cellular disfunction but as an organismal process. 
All the cells within an organism are undergoing aging, and not all of them
are aging simultaneously. Similarly, different tissues are aging differently. XXX

Aging research was inaugurated following the isolation of the first 
long-lived strains in C. elegans. In the past three decades, the nematode played a fundamental 
role in aging research. It is a powerful model organism when it comes to studying aging: 

- It has a short life cycle (~ 21 days in normal conditions)
- Mutants can be easily generated and phenotypically screened for aging defects
- Its genome has been fully sequenced and presents fundamental resemblances with 
that of more complex metazoans. 

In this project, we will study XXX...

To build the HTML version of this set of files, you can use: 
```{r eval = FALSE}
bookdown::render_book('01-Day1.Rmd', output_format = 'bookdown::gitbook')
```